### ISSUE TITLE
请问能将OpenSSL的包一起构建出来嘛？

### ISSUE THREAD

**Issue by xxoobb** [boypt/openssh-rpms#10]
有幸使用您的脚本，因为OpenSSL也经常被扫出漏洞，请问：能否考虑将静态链接的OpenSSL改为构建实体包。

**Comment by amwu** [comment]
> 有幸使用您的脚本，因为OpenSSL也经常被扫出漏洞，请问：能否考虑将静态链接的OpenSSL改为构建实体包。

https://gitee.com/OnlyVersion/openssh-rpms

**Comment by boypt** [comment]
openssl is not a service but a dynamic linked library, upgrading openssl package could cause many packages fail to run.

openssl can upgrade by only recompile the service programs themselves.
