### ISSUE TITLE
rpm dist undefined, please specify: el5 el6 el7

### ISSUE THREAD

**Issue by Aliphat** [boypt/openssh-rpms#11]
rpm dist undefined, please specify: el5 el6 el7
![image](https://github.com/boypt/openssh-rpms/assets/30551823/0a7cb641-ccc1-4b30-87fd-c920b5f4d92e)

请问这个问题如何解决？
May I ask how to solve this problem?

**Comment by mxdblcf** [comment]
去掉sudo

**Comment by boypt** [comment]
the script can not detect which os you are using, you should try `./compile.sh el7`
