### ISSUE TITLE
 recommended to add parameters in the installation script

### ISSUE THREAD

**Issue by mixyoung** [boypt/openssh-rpms#28]
yum --disablerepo=* localinstall -y  --allowerasing

yum --disablerepo=* localinstall -y
In this section you should add installation parameters
mistake:
 Problem: cannot install both openssh-9.8p1-1.an8.x86_64 from @commandline and openssh-8.0p1-20.0.4.an8.x86_64 from @System
  - package openssh-askpass-8.0p1-20.0.4.an8.x86_64 from @System requires openssh = 8.0p1-20.0.4.an8, but none of the providers can be installed
  - Conflicting requests
  - Issues with the installed package openssh-askpass-8.0p1-20.0.4.an8.x86_64
(Try adding '--allowerasing' to the command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to not use only the best candidate for a package)

**Comment by boypt** [comment]
updated README in 9d2db89

 thanks for the info 👍
