### ISSUE TITLE
编译其他 ssh 版本，只需要更改 version.env 文件么？

### ISSUE THREAD

**Issue by saodis** [boypt/openssh-rpms#7]
师傅 编译其他 ssh 版本，只需要更改 version.env 文件么？

PKGREL 是 ssh 名称 P 后面的数字么？

**Comment by boypt** [comment]
Correct.

PKGREL is the number attached to the package version, example `PKGREL=3` generate the following rpm:
openssh-9.4p1-3.el6.x86_64.rpm
