### ISSUE TITLE
RPM 构建错误:/var/tmp/rpm-tmp.NUKkwS (%prep) 退出状态不好

### ISSUE THREAD

**Issue by Yang000111** [boypt/openssh-rpms#9]
./compile.sh  occur a error

+ ./config shared zlib -fPIC
Can't locate IPC/Cmd.pm in @INC (@INC contains: /opt/openssh-rpms-main/el7/BUILD/openssh-9.5p1/openssl/util/perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /opt/openssh-rpms-main/el7/BUILD/openssh-9.5p1/openssl/external/perl/Text-Template-1.56/lib) at /opt/openssh-rpms-main/el7/BUILD/openssh-9.5p1/openssl/util/perl/OpenSSL/config.pm line 19.
BEGIN failed--compilation aborted at /opt/openssh-rpms-main/el7/BUILD/openssh-9.5p1/openssl/util/perl/OpenSSL/config.pm line 19.
Compilation failed in require at /opt/openssh-rpms-main/el7/BUILD/openssh-9.5p1/openssl/Configure line 23.
BEGIN failed--compilation aborted at /opt/openssh-rpms-main/el7/BUILD/openssh-9.5p1/openssl/Configure line 23.
错误：/var/tmp/rpm-tmp.NUKkwS (%prep) 退出状态不好

RPM 构建错误：
    /var/tmp/rpm-tmp.NUKkwS (%prep) 退出状态不好
Aborted, error 1 in command: rpmbuild -ba SPECS/openssh.spec --target $(uname -m) --define "_topdir $PWD" --define "opensslver ${OPENSSLVER}" --define "opensshver ${OPENSSHVER}" --define "opensshpkgrel ${PKGREL}" --define 'no_gtk2 1' --define 'skip_gnome_askpass 1' --define 'skip_x11_askpass 1'
trap: 用法:trap [-lp] [[参数] 信号声明 ...]

**Comment by herry1234** [comment]
installing perl-IPC-Cmd would help:  

> yum install perl-IPC-Cmd
